// gyf607020/src/components/FilterBar.tsx
import { Search, RotateCcw, Download, Phone, Calendar, Filter } from 'lucide-react';
import { useStore, buildQuery } from '@/store/useStore';
import type { RecordStatus } from '@shared/types';

const statusOptions: { value: RecordStatus | ''; label: string }[] = [
  { value: '', label: '全部状态' },
  { value: 'pending', label: '待复核' },
  { value: 'approved', label: '已通过' },
  { value: 'rejected', label: '已拒绝' },
  { value: 'bad_data', label: '坏数据' },
];

export default function FilterBar({ onExport }: { onExport: () => void }) {
  const { filters, setFilters, resetFilters, normalCount, fetchRecords } = useStore();

  return (
    <div className="bg-white rounded-card p-5 shadow-card border border-cream-200 animate-fade-in">
      <div className="flex items-center gap-2 mb-4">
        <Filter className="w-4 h-4 text-brand-500" />
        <h3 className="font-serif font-medium text-gray-800">筛选条件</h3>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="space-y-1">
          <label className="text-xs text-gray-500 flex items-center gap-1">
            <Phone className="w-3.5 h-3.5" />
            家长手机号
          </label>
          <input
            type="text"
            value={filters.phone || ''}
            placeholder="输入手机号搜索，支持模糊匹配"
            onChange={(e) => setFilters({ phone: e.target.value })}
            className="w-full px-3 py-2 border border-cream-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-brand-200 focus:border-brand-400 transition-all bg-cream-50/50"
          />
        </div>
        <div className="space-y-1">
          <label className="text-xs text-gray-500">状态</label>
          <select
            value={filters.status || ''}
            onChange={(e) => setFilters({ status: (e.target.value as RecordStatus) || undefined })}
            className="w-full px-3 py-2 border border-cream-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-brand-200 focus:border-brand-400 transition-all bg-cream-50/50 appearance-none"
          >
            {statusOptions.map((o) => (
              <option key={o.value} value={o.value}>
              {o.label}
            </option>
            ))}
          </select>
        </div>
        <div className="space-y-1">
          <label className="text-xs text-gray-500 flex items-center gap-1">
            <Calendar className="w-3.5 h-3.5" />
            开始日期
          </label>
          <input
            type="date"
            value={filters.startDate || ''}
            onChange={(e) => setFilters({ startDate: e.target.value })}
            className="w-full px-3 py-2 border border-cream-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-brand-200 focus:border-brand-400 transition-all bg-cream-50/50"
          />
        </div>
        <div className="space-y-1">
          <label className="text-xs text-gray-500">结束日期</label>
          <input
            type="date"
            value={filters.endDate || ''}
            onChange={(e) => setFilters({ endDate: e.target.value })}
            className="w-full px-3 py-2 border border-cream-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-brand-200 focus:border-brand-400 transition-all bg-cream-50/50"
          />
        </div>
      </div>
      <div className="flex items-center gap-3 mt-4 flex-wrap">
        <label className="flex items-center gap-1.5 text-sm text-gray-600 cursor-pointer select-none">
          <input
            type="checkbox"
            checked={!!filters.includeBadData}
            onChange={(e) => setFilters({ includeBadData: e.target.checked })}
            className="w-4 h-4 text-brand-500 border-cream-300 rounded focus:ring-brand-400"
          />
          包含坏数据（已隔离）
        </label>
        <div className="flex-1" />
        <button
          onClick={resetFilters}
          className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg border border-cream-300 text-gray-600 hover:bg-cream-100 hover:text-gray-800 text-sm transition-all"
        >
          <RotateCcw className="w-4 h-4" />
          重置
        </button>
        <button
          onClick={() => fetchRecords()}
          className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg bg-brand-400 text-white shadow hover:bg-brand-500 hover:-translate-y-0.5 hover:shadow-md text-sm font-medium transition-all"
        >
          <Search className="w-4 h-4" />
          查询
        </button>
        <button
          onClick={onExport}
          disabled={normalCount === 0}
          className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg bg-green-500 text-white shadow hover:bg-green-600 hover:-translate-y-0.5 hover:shadow-md text-sm font-medium transition-all disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:translate-y-0 disabled:hover:shadow-none"
        >
          <Download className="w-4 h-4" />
          导出家长交接表（{normalCount} 条）
        </button>
      </div>
    </div>
  );
}

export { buildQuery };

// 015-gyf609015/src/components/FilterBar.vue
<script setup lang="ts">
import { useFilterStore } from '@/stores/filter'
import { useUIStore } from '@/stores/ui'
import { useSampleStore } from '@/stores/sample'
import { STATUS_OPTIONS } from '@/types'
import { Search, Plus, Download, RotateCcw, Calendar, Filter, X } from 'lucide-vue-next'

const filter = useFilterStore()
const ui = useUIStore()
const sample = useSampleStore()

const statusOptions = STATUS_OPTIONS

function onExport() {
  ui.openExport()
}

function onCreate() {
  ui.openCreate()
}

function onResetAll() {
  filter.reset()
  sample.resetToMock()
}
</script>

<template>
  <div class="bg-industrial-800 rounded-md shadow-card overflow-hidden">
    <div class="px-5 py-4 flex flex-wrap items-center gap-4 border-b border-industrial-700/50">
      <div class="flex items-center gap-3">
        <Filter :size="18" class="text-industrial-300" />
        <h2 class="font-serif font-bold text-white text-lg tracking-wide">幕墙样板封样对账</h2>
      </div>
      <div class="flex-1"></div>
      <div class="flex items-center gap-2">
        <button
          class="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs rounded border border-industrial-600 text-industrial-200 hover:bg-industrial-700/50 transition-colors"
          @click="onResetAll"
        >
          <RotateCcw :size="14" />
          重置数据
        </button>
        <button
          class="inline-flex items-center gap-1.5 px-4 py-1.5 text-xs rounded bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors"
          @click="onExport"
        >
          <Download :size="14" />
          导出对账表
          <span class="bg-amber-gold-500 text-industrial-900 px-1.5 py-0.5 rounded-full text-[10px] font-bold">
            {{ filter.filteredSamples.length }}
          </span>
        </button>
        <button
          class="inline-flex items-center gap-1.5 px-4 py-1.5 text-xs rounded bg-amber-gold-500 hover:bg-amber-gold-400 text-industrial-900 font-bold transition-colors shadow-sm"
          @click="onCreate"
        >
          <Plus :size="14" />
          新增样板
        </button>
      </div>
    </div>

    <div class="px-5 py-4 flex flex-wrap items-center gap-4">
      <div class="flex items-center gap-1 rounded bg-industrial-900/50 p-1 border border-industrial-700/50">
        <button
          v-for="opt in statusOptions"
          :key="opt.value"
          :class="[
            'px-3 py-1.5 text-xs rounded font-medium transition-all',
            filter.state.status === opt.value
              ? 'bg-white text-industrial-800 shadow-sm'
              : 'text-industrial-200 hover:text-white hover:bg-white/5',
          ]"
          @click="filter.setStatus(opt.value)"
        >
          {{ opt.label }}
        </button>
      </div>

      <div class="relative min-w-[260px]">
        <Search :size="14" class="absolute left-3 top-1/2 -translate-y-1/2 text-industrial-400" />
        <input
          :value="filter.state.keyword"
          type="text"
          placeholder="搜索样板编号/厂家/批次..."
          class="w-full h-9 pl-9 pr-8 rounded bg-industrial-900/50 border border-industrial-700/50 text-white placeholder-industrial-400 text-xs focus:outline-none focus:border-amber-gold-500/70 focus:ring-1 focus:ring-amber-gold-500/30 transition-colors"
          @input="(e: Event) => filter.setKeyword((e.target as HTMLInputElement).value)"
        />
        <button
          v-if="filter.state.keyword"
          class="absolute right-2 top-1/2 -translate-y-1/2 p-1 rounded hover:bg-white/10 text-industrial-400"
          @click="filter.setKeyword('')"
        >
          <X :size="12" />
        </button>
      </div>

      <div class="flex items-center gap-2">
        <Calendar :size="14" class="text-industrial-400" />
        <input
          :value="filter.state.dateStart"
          type="date"
          class="h-9 px-2 rounded bg-industrial-900/50 border border-industrial-700/50 text-white text-xs focus:outline-none focus:border-amber-gold-500/70"
          @change="(e: Event) => filter.setDateRange((e.target as HTMLInputElement).value, filter.state.dateEnd)"
        />
        <span class="text-industrial-500 text-xs">至</span>
        <input
          :value="filter.state.dateEnd"
          type="date"
          class="h-9 px-2 rounded bg-industrial-900/50 border border-industrial-700/50 text-white text-xs focus:outline-none focus:border-amber-gold-500/70"
          @change="(e: Event) => filter.setDateRange(filter.state.dateStart, (e.target as HTMLInputElement).value)"
        />
        <button
          v-if="filter.state.dateStart || filter.state.dateEnd"
          class="text-xs text-industrial-400 hover:text-white underline underline-offset-2 ml-1"
          @click="filter.setDateRange('', '')"
        >
          清除
        </button>
      </div>

      <div class="flex-1"></div>

      <div class="text-xs text-industrial-300">
        筛选结果
        <span class="text-amber-gold-400 font-bold ml-1">{{ filter.filteredSamples.length }}</span>
        <span class="text-industrial-500 mx-1">/</span>
        <span class="text-industrial-400">{{ sample.samples.length }}</span>
        条
      </div>
    </div>
  </div>
</template>
