// gyf607019/src/components/StatusBadge.tsx
import { STATUS_LABEL, STATUS_COLOR, type AuthorizationStatus } from '@/types';
import { AlertTriangle, CheckCircle2, Clock, XCircle } from 'lucide-react';

const statusIcons = {
  pending: Clock,
  approved: CheckCircle2,
  rejected: XCircle,
  partial: AlertTriangle,
};

interface Props {
  status: AuthorizationStatus;
  size?: 'sm' | 'md';
}

export default function StatusBadge({ status, size = 'sm' }: Props) {
  const Icon = statusIcons[status];
  const sizeClass = size === 'sm' ? 'px-2 py-0.5 text-xs gap-1' : 'px-3 py-1 text-sm gap-1.5';
  return (
    <span
      className={`inline-flex items-center rounded-full border font-medium ${STATUS_COLOR[status]} ${sizeClass}`}
    >
      <Icon className={size === 'sm' ? 'w-3 h-3' : 'w-4 h-4'} />
      <span>{STATUS_LABEL[status]}</span>
    </span>
  );
}

// 015-gyf609015/src/components/StatusBadge.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { SampleStatus } from '@/types'
import { CheckCircle2, Clock, XCircle } from 'lucide-vue-next'

const props = defineProps<{
  status: SampleStatus
  size?: 'sm' | 'md'
}>()

const config = computed(() => {
  switch (props.status) {
    case 'available':
      return {
        label: '可用',
        bg: 'bg-amber-gold-50',
        text: 'text-amber-gold-700',
        border: 'border-amber-gold-300',
        ring: 'ring-amber-gold-200',
        Icon: CheckCircle2,
      }
    case 'pending':
      return {
        label: '待确认',
        bg: 'bg-warn-orange-50',
        text: 'text-warn-orange-700',
        border: 'border-warn-orange-300',
        ring: 'ring-warn-orange-200',
        Icon: Clock,
      }
    case 'rejected':
      return {
        label: '退回',
        bg: 'bg-alert-red-50',
        text: 'text-alert-red-700',
        border: 'border-alert-red-300',
        ring: 'ring-alert-red-200',
        Icon: XCircle,
      }
    default:
      return {
        label: props.status,
        bg: 'bg-cool-gray-50',
        text: 'text-cool-gray-700',
        border: 'border-cool-gray-300',
        ring: 'ring-cool-gray-200',
        Icon: Clock,
      }
  }
})

const sizeCls = computed(() => props.size === 'sm' ? 'px-2 py-0.5 text-xs gap-1' : 'px-3 py-1 text-sm gap-1.5')
</script>

<template>
  <span
    :class="[
      'inline-flex items-center rounded border font-medium ring-1 ring-inset',
      config.bg, config.text, config.border, config.ring, sizeCls,
    ]"
  >
    <component :is="config.Icon" :size="size === 'sm' ? 12 : 14" />
    {{ config.label }}
  </span>
</template>
