// gyf607008/src/components/StatusBadge.tsx
import type { RecordStatus } from '@shared/types';

interface Props {
  status: RecordStatus;
}

const config: Record<RecordStatus, { label: string; dot: string; text: string; bg: string; border: string }> = {
  normal: {
    label: '正常',
    dot: 'bg-status-normal',
    text: 'text-status-normal',
    bg: 'bg-emerald-950/40',
    border: 'border-emerald-800/60',
  },
  pending: {
    label: '待复核',
    dot: 'bg-status-pending',
    text: 'text-status-pending',
    bg: 'bg-amber-950/40',
    border: 'border-amber-800/60',
  },
  abnormal: {
    label: '异常',
    dot: 'bg-status-abnormal',
    text: 'text-status-abnormal',
    bg: 'bg-red-950/40',
    border: 'border-red-800/60',
  },
};

export function StatusBadge({ status }: Props) {
  const c = config[status];
  return (
    <span
      className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-xs font-medium border ${c.bg} ${c.text} ${c.border}`}
    >
      <span className={`w-1.5 h-1.5 rounded-full ${c.dot}`} />
      {c.label}
    </span>
  );
}

// 015-gyf609015/src/components/StatusBadge.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { SampleStatus } from '@/types'
import { CheckCircle2, Clock, XCircle } from 'lucide-vue-next'

const props = defineProps<{
  status: SampleStatus
  size?: 'sm' | 'md'
}>()

const config = computed(() => {
  switch (props.status) {
    case 'available':
      return {
        label: '可用',
        bg: 'bg-amber-gold-50',
        text: 'text-amber-gold-700',
        border: 'border-amber-gold-300',
        ring: 'ring-amber-gold-200',
        Icon: CheckCircle2,
      }
    case 'pending':
      return {
        label: '待确认',
        bg: 'bg-warn-orange-50',
        text: 'text-warn-orange-700',
        border: 'border-warn-orange-300',
        ring: 'ring-warn-orange-200',
        Icon: Clock,
      }
    case 'rejected':
      return {
        label: '退回',
        bg: 'bg-alert-red-50',
        text: 'text-alert-red-700',
        border: 'border-alert-red-300',
        ring: 'ring-alert-red-200',
        Icon: XCircle,
      }
    default:
      return {
        label: props.status,
        bg: 'bg-cool-gray-50',
        text: 'text-cool-gray-700',
        border: 'border-cool-gray-300',
        ring: 'ring-cool-gray-200',
        Icon: Clock,
      }
  }
})

const sizeCls = computed(() => props.size === 'sm' ? 'px-2 py-0.5 text-xs gap-1' : 'px-3 py-1 text-sm gap-1.5')
</script>

<template>
  <span
    :class="[
      'inline-flex items-center rounded border font-medium ring-1 ring-inset',
      config.bg, config.text, config.border, config.ring, sizeCls,
    ]"
  >
    <component :is="config.Icon" :size="size === 'sm' ? 12 : 14" />
    {{ config.label }}
  </span>
</template>
