// change-impact-dashboard/src/App.vue
<template>
  <div class="min-h-screen bg-slate-50">
    <header class="bg-white border-b border-slate-200 sticky top-0 z-30">
      <div class="max-w-7xl mx-auto px-4 py-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-3">
            <div class="w-10 h-10 bg-primary-600 rounded-xl flex items-center justify-center">
              <GitCompare class="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 class="text-xl font-bold text-slate-800">设计变更影响对照页</h1>
              <p class="text-xs text-slate-500">设计变更对工序、成本和已施工区域影响分析</p>
            </div>
          </div>
          
          <div class="flex items-center gap-3">
            <button 
              @click="openImportWizard"
              class="btn-primary text-sm"
            >
              <Upload class="w-4 h-4 mr-1" />
              导入变更
            </button>
            
            <div class="relative" ref="exportDropdownRef">
              <button 
                @click="showExportMenu = !showExportMenu"
                class="btn-secondary text-sm"
              >
                <Download class="w-4 h-4 mr-1" />
                导出
                <ChevronDown class="w-4 h-4 ml-1" />
              </button>
              
              <Transition name="fade">
                <div 
                  v-if="showExportMenu"
                  class="absolute right-0 top-full mt-2 w-56 bg-white rounded-xl shadow-lg border border-slate-200 py-2 z-50"
                >
                  <button 
                    @click="handleExportExcel"
                    class="w-full px-4 py-2 text-sm text-left hover:bg-slate-50 flex items-center gap-2"
                  >
                    <FileSpreadsheet class="w-4 h-4 text-emerald-500" />
                    导出 Excel 清单
                  </button>
                  <button 
                    @click="handleExportReport"
                    class="w-full px-4 py-2 text-sm text-left hover:bg-slate-50 flex items-center gap-2"
                  >
                    <FileText class="w-4 h-4 text-blue-500" />
                    导出影响报告
                  </button>
                  <button 
                    @click="handleExportChecklist"
                    class="w-full px-4 py-2 text-sm text-left hover:bg-slate-50 flex items-center gap-2"
                  >
                    <ListChecks class="w-4 h-4 text-amber-500" />
                    导出核对清单
                  </button>
                  <div class="border-t border-slate-100 my-1"></div>
                  <button 
                    @click="handleVerifyData"
                    class="w-full px-4 py-2 text-sm text-left hover:bg-slate-50 flex items-center gap-2"
                  >
                    <ShieldCheck class="w-4 h-4 text-primary-500" />
                    验证数据一致性
                  </button>
                </div>
              </Transition>
            </div>
            
            <button 
              @click="showHelpModal = true"
              class="p-2 text-slate-500 hover:bg-slate-100 rounded-lg transition-colors"
              title="使用帮助"
            >
              <HelpCircle class="w-5 h-5" />
            </button>
            
            <button 
              @click="handleReset"
              class="p-2 text-slate-500 hover:bg-slate-100 rounded-lg transition-colors"
              title="重置数据"
            >
              <RefreshCw class="w-5 h-5" />
            </button>
          </div>
        </div>
      </div>
    </header>
    
    <main class="max-w-7xl mx-auto px-4 py-6">
      <div class="space-y-6">
        <StatsCards />
        
        <div class="grid grid-cols-12 gap-6">
          <div class="col-span-12 lg:col-span-3 space-y-4">
            <FloorSelector />
            <FilterPanel />
            <MajorBreakdown />
          </div>
          
          <div class="col-span-12 lg:col-span-9">
            <ChangeList />
          </div>
        </div>
      </div>
    </main>
    
    <DetailDrawer />
    <RevertModal />
    <ImportWizard 
      :is-open="isImportWizardOpen" 
      @close="isImportWizardOpen = false" 
    />
    
    <div v-if="showHelpModal" class="modal-backdrop" @click.self="showHelpModal = false">
      <div class="modal-panel max-w-2xl">
        <div class="p-4 border-b border-slate-200 flex items-center justify-between">
          <h3 class="text-lg font-semibold text-slate-800 flex items-center gap-2">
            <HelpCircle class="w-5 h-5 text-primary-600" />
            使用帮助
          </h3>
          <button @click="showHelpModal = false" class="p-2 hover:bg-slate-100 rounded-lg transition-colors">
            <X class="w-5 h-5 text-slate-500" />
          </button>
        </div>
        <div class="p-4 max-h-[70vh] overflow-y-auto scrollbar-thin space-y-4">
          <div>
            <h4 class="text-sm font-semibold text-slate-700 mb-2">一、快速开始</h4>
            <ol class="text-sm text-slate-600 space-y-1 list-decimal list-inside">
              <li>首次打开会自动加载9条样例变更数据</li>
              <li>点击左侧「楼层选择」切换楼层，右侧统计和列表会联动更新</li>
              <li>使用「筛选条件」按专业、责任人、影响等级等筛选</li>
              <li>点击变更列表中的行查看详细信息</li>
            </ol>
          </div>
          
          <div>
            <h4 class="text-sm font-semibold text-slate-700 mb-2">二、核心功能说明</h4>
            <div class="space-y-2">
              <div class="p-3 bg-blue-50 rounded-lg">
                <div class="text-sm font-medium text-blue-700 mb-1">🔄 楼层联动</div>
                <div class="text-xs text-blue-600">切换楼层时，统计卡片、专业分布、变更列表会自动筛选对应楼层的数据，显示该楼层的成本、进度、责任专业影响。</div>
              </div>
              <div class="p-3 bg-amber-50 rounded-lg">
                <div class="text-sm font-medium text-amber-700 mb-1">⚠️ 已施工标记</div>
                <div class="text-xs text-amber-600">红色边框表示该区域已施工，变更会产生返工成本，需要特别关注。</div>
              </div>
              <div class="p-3 bg-green-50 rounded-lg">
                <div class="text-sm font-medium text-green-700 mb-1">↩️ 撤回机制</div>
                <div class="text-xs text-green-600">已施工且待确认的变更支持撤回误判，旧的影响等级、成本、进度数据和处理人会保留在历史记录中。</div>
              </div>
              <div class="p-3 bg-purple-50 rounded-lg">
                <div class="text-sm font-medium text-purple-700 mb-1">📊 版本对比</div>
                <div class="text-xs text-purple-600">设计院补发新版变更函时，可创建新版本并对比历史版本差异。</div>
              </div>
            </div>
          </div>
          
          <div>
            <h4 class="text-sm font-semibold text-slate-700 mb-2">三、数据刷新验证步骤</h4>
            <ol class="text-sm text-slate-600 space-y-1 list-decimal list-inside">
              <li>点击「导出」→「验证数据一致性」，记录当前哈希值</li>
              <li>按 F5 刷新整个页面</li>
              <li>确认筛选条件保持不变</li>
              <li>确认待确认数量保持不变</li>
              <li>再次点击「导出」→「验证数据一致性」</li>
              <li>确认哈希值与刷新前完全一致</li>
            </ol>
          </div>
          
          <div>
            <h4 class="text-sm font-semibold text-slate-700 mb-2">四、图例说明</h4>
            <div class="grid grid-cols-2 gap-2 text-xs">
              <div class="flex items-center gap-2">
                <span class="w-3 h-3 rounded bg-red-500"></span>
                <span class="text-slate-600">高影响 / 已施工</span>
              </div>
              <div class="flex items-center gap-2">
                <span class="w-3 h-3 rounded bg-amber-500"></span>
                <span class="text-slate-600">中影响 / 部分施工</span>
              </div>
              <div class="flex items-center gap-2">
                <span class="w-3 h-3 rounded bg-green-500"></span>
                <span class="text-slate-600">低影响</span>
              </div>
              <div class="flex items-center gap-2">
                <span class="w-3 h-3 rounded bg-blue-500"></span>
                <span class="text-slate-600">仅图纸</span>
              </div>
            </div>
          </div>
        </div>
        <div class="p-4 border-t border-slate-200 bg-slate-50 text-xs text-slate-500">
          <p>所有数据存储在浏览器本地 localStorage 中，清理浏览器数据会导致数据丢失。</p>
          <p class="mt-1">数据哈希：<span class="font-mono">{{ store.change.dataHash }}</span></p>
        </div>
      </div>
    </div>
    
    <div v-if="showVerifyModal" class="modal-backdrop" @click.self="showVerifyModal = false">
      <div class="modal-panel max-w-md">
        <div class="p-4 border-b border-slate-200 flex items-center justify-between">
          <h3 class="text-lg font-semibold text-slate-800 flex items-center gap-2">
            <ShieldCheck class="w-5 h-5 text-primary-600" />
            数据一致性验证
          </h3>
          <button @click="showVerifyModal = false" class="p-2 hover:bg-slate-100 rounded-lg transition-colors">
            <X class="w-5 h-5 text-slate-500" />
          </button>
        </div>
        <div class="p-6">
          <div v-if="verifyResult" class="space-y-4">
            <div class="text-center">
              <div :class="[
                'w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-3',
                verifyResult.isConsistent ? 'bg-green-100' : 'bg-red-100'
              ]">
                <Check v-if="verifyResult.isConsistent" class="w-8 h-8 text-green-600" />
                <AlertTriangle v-else class="w-8 h-8 text-red-600" />
              </div>
              <div :class="[
                'text-lg font-semibold',
                verifyResult.isConsistent ? 'text-green-600' : 'text-red-600'
              ]">
                {{ verifyResult.isConsistent ? '数据一致 ✓' : '数据不一致 ✗' }}
              </div>
            </div>
            
            <div class="p-4 bg-slate-50 rounded-lg space-y-2 text-sm">
              <div class="flex justify-between">
                <span class="text-slate-500">记录总数</span>
                <span class="font-medium text-slate-700">{{ verifyResult.recordCount }} 条</span>
              </div>
              <div class="flex justify-between">
                <span class="text-slate-500">存储哈希值</span>
                <span class="font-mono text-slate-700">{{ verifyResult.storedHash }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-slate-500">当前哈希值</span>
                <span class="font-mono text-slate-700">{{ verifyResult.currentHash }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-slate-500">最后更新</span>
                <span class="text-slate-700">{{ formatDateTime(verifyResult.lastUpdated) }}</span>
              </div>
            </div>
            
            <p class="text-xs text-slate-500 text-center">
              刷新浏览器后重新验证，如哈希值相同则证明数据未发生变化
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { 
  Upload, Download, ChevronDown, HelpCircle, RefreshCw, X,
  GitCompare, FileSpreadsheet, FileText, ListChecks, ShieldCheck,
  Check, AlertTriangle
} from 'lucide-vue-next';
import { useChangeStore } from './stores/changeStore';
import { exportToExcel, exportImpactReport, exportChecklist } from './utils/importExport';
import { formatDateTime } from './utils/storage';

import StatsCards from './components/StatsCards.vue';
import FloorSelector from './components/FloorSelector.vue';
import FilterPanel from './components/FilterPanel.vue';
import MajorBreakdown from './components/MajorBreakdown.vue';
import ChangeList from './components/ChangeList.vue';
import DetailDrawer from './components/DetailDrawer.vue';
import RevertModal from './components/RevertModal.vue';
import ImportWizard from './components/ImportWizard.vue';

const store = { change: useChangeStore() };

const showExportMenu = ref(false);
const showHelpModal = ref(false);
const showVerifyModal = ref(false);
const isImportWizardOpen = ref(false);
const verifyResult = ref(null);
const exportDropdownRef = ref(null);

const openImportWizard = () => {
  isImportWizardOpen.value = true;
  showExportMenu.value = false;
};

const handleExportExcel = () => {
  exportToExcel(store.change.filteredChanges);
  showExportMenu.value = false;
};

const handleExportReport = () => {
  exportImpactReport(store.change.changes, store.change.selectedFloorId);
  showExportMenu.value = false;
};

const handleExportChecklist = () => {
  exportChecklist(store.change.changes);
  showExportMenu.value = false;
};

const handleVerifyData = () => {
  verifyResult.value = store.change.verifyDataConsistency();
  showVerifyModal.value = true;
  showExportMenu.value = false;
};

const handleReset = () => {
  if (confirm('确定要重置所有数据吗？这将恢复为初始样例数据。')) {
    store.change.resetAllData();
  }
};

const handleClickOutside = (event) => {
  if (exportDropdownRef.value && !exportDropdownRef.value.contains(event.target)) {
    showExportMenu.value = false;
  }
};

onMounted(() => {
  store.change.loadStoredData();
  document.addEventListener('click', handleClickOutside);
});
</script>

<style>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// annotation-tracker/src/App.jsx
import { useState } from 'react';
import { FileSpreadsheet, Upload, Download, RotateCcw, FileDown, ListChecks, FileText, HelpCircle } from 'lucide-react';
import { useInitialize, resetAllData } from './hooks/useInitialize';
import { useAnnotations } from './hooks/useAnnotations';
import { StatsCards, StatusDistribution } from './components/StatsCards';
import { FilterPanel } from './components/FilterPanel';
import { ProblemSection } from './components/ProblemSection';
import { AnnotationList } from './components/AnnotationList';
import { DetailDrawer } from './components/DetailDrawer';
import { ImportWizard } from './components/ImportWizard';
import { exportToExcel, exportSummary, exportChecklist, generateHash } from './utils/export';
import { getRepliesByAnnotationId } from './db/operations';

function App() {
  const { isLoading, error: initError, isInitialized } = useInitialize();
  const {
    annotations,
    normalAnnotations,
    problemAnnotations,
    loading,
    error,
    stats,
    filters,
    updateFilter,
    clearFilters,
    refresh,
    removeAnnotation,
    changeStatus
  } = useAnnotations();

  const [selectedAnnotation, setSelectedAnnotation] = useState(null);
  const [showImportWizard, setShowImportWizard] = useState(false);
  const [showHelp, setShowHelp] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [lastHash, setLastHash] = useState(null);

  const handleRefresh = async () => {
    setRefreshing(true);
    await refresh();
    setRefreshing(false);
    
    const currentHash = generateHash(annotations.map(a => ({
      annotationNo: a.annotationNo,
      status: a.status,
      updatedAt: a.updatedAt
    })));
    
    if (lastHash && currentHash !== lastHash) {
      console.log(`数据已更新: ${lastHash} → ${currentHash}`);
    }
    setLastHash(currentHash);
  };

  const handleResetData = async () => {
    if (confirm('确定要重置所有数据吗？这将恢复到初始样例状态，所有修改都会丢失。')) {
      try {
        await resetAllData();
        await refresh();
        alert('数据已重置');
      } catch (err) {
        alert('重置失败：' + err.message);
      }
    }
  };

  const handleExportExcel = () => {
    exportToExcel(annotations, `图纸会审批注清单_${formatDate()}.xlsx`);
  };

  const handleExportSummary = async () => {
    const replies = await getRepliesForAnnotations(annotations);
    exportSummary(annotations, replies, `会审批注回复摘要_${formatDate()}.txt`);
  };

  const handleExportChecklist = () => {
    exportChecklist(annotations, `会审问题追踪核对表_${formatDate()}.txt`);
  };

  const handleImportSuccess = () => {
    setShowImportWizard(false);
    refresh();
  };

  const handleVerifyData = async () => {
    const currentHash = generateHash(annotations.map(a => ({
      annotationNo: a.annotationNo,
      status: a.status,
      description: a.description,
      assignee: a.assignee
    })));
    
    const replies = await getRepliesForAnnotations(annotations);
    const replyCount = replies.length;
    
    alert(
      `数据一致性验证\n\n` +
      `总批注数：${annotations.length}\n` +
      `总回复数：${replyCount}\n` +
      `数据哈希：${currentHash}\n\n` +
      `刷新页面后，此哈希值应保持不变。\n` +
      `导出的 Excel 摘要与当前列表数据一致。`
    );
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin w-12 h-12 border-4 border-primary-600 border-t-transparent rounded-full mx-auto mb-4"></div>
          <p className="text-slate-600">正在初始化数据...</p>
        </div>
      </div>
    );
  }

  if (initError) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-center max-w-md">
          <div className="text-red-500 text-6xl mb-4">⚠️</div>
          <h2 className="text-xl font-semibold text-slate-800 mb-2">初始化失败</h2>
          <p className="text-slate-600 mb-4">{initError}</p>
          <button onClick={() => window.location.reload()} className="btn-primary">
            刷新重试
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="bg-white border-b border-slate-200 sticky top-0 z-30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-primary-600 rounded-xl flex items-center justify-center">
                <FileSpreadsheet className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-lg font-bold text-slate-800">
                  图纸会审批注追踪板
                </h1>
                <p className="text-xs text-slate-500">
                  多专业会审意见管理 · 责任流转追踪
                </p>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <div className="relative group">
                <button
                  onClick={() => setShowImportWizard(true)}
                  className="btn-primary"
                >
                  <Upload className="w-4 h-4 mr-2" />
                  导入会审清单
                </button>
              </div>

              <div className="relative group">
                <button className="btn-secondary">
                  <Download className="w-4 h-4 mr-2" />
                  导出
                </button>
                <div className="absolute right-0 top-full mt-1 bg-white rounded-lg shadow-lg border border-slate-200 py-1 w-48 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all z-40">
                  <button
                    onClick={handleExportExcel}
                    className="w-full px-4 py-2 text-left text-sm hover:bg-slate-50 flex items-center gap-2"
                  >
                    <FileSpreadsheet className="w-4 h-4 text-green-600" />
                    导出 Excel 清单
                  </button>
                  <button
                    onClick={handleExportSummary}
                    className="w-full px-4 py-2 text-left text-sm hover:bg-slate-50 flex items-center gap-2"
                  >
                    <FileText className="w-4 h-4 text-blue-600" />
                    导出回复摘要
                  </button>
                  <button
                    onClick={handleExportChecklist}
                    className="w-full px-4 py-2 text-left text-sm hover:bg-slate-50 flex items-center gap-2"
                  >
                    <ListChecks className="w-4 h-4 text-amber-600" />
                    导出核对清单
                  </button>
                  <div className="border-t border-slate-100 my-1"></div>
                  <button
                    onClick={handleVerifyData}
                    className="w-full px-4 py-2 text-left text-sm hover:bg-slate-50 flex items-center gap-2 text-slate-600"
                  >
                    <FileDown className="w-4 h-4" />
                    验证数据一致性
                  </button>
                </div>
              </div>

              <button
                onClick={handleResetData}
                className="btn-secondary"
                title="重置为初始样例数据"
              >
                <RotateCcw className="w-4 h-4 mr-2" />
                重置数据
              </button>

              <button
                onClick={() => setShowHelp(true)}
                className="p-2 hover:bg-slate-100 rounded-lg transition-colors"
              >
                <HelpCircle className="w-5 h-5 text-slate-500" />
              </button>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <StatsCards stats={stats} onRefresh={handleRefresh} refreshing={refreshing} />

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          <div className="lg:col-span-3">
            <FilterPanel
              filters={filters}
              updateFilter={updateFilter}
              clearFilters={clearFilters}
            />

            {problemAnnotations.length > 0 && (
              <ProblemSection
                annotations={problemAnnotations}
                onRefresh={refresh}
                onViewDetail={setSelectedAnnotation}
              />
            )}

            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-slate-800">
                正常记录
                <span className="ml-2 text-sm font-normal text-slate-500">
                  ({normalAnnotations.length} 条)
                </span>
              </h2>
              {error && (
                <span className="text-sm text-red-600">{error}</span>
              )}
            </div>

            <AnnotationList
              annotations={normalAnnotations}
              onViewDetail={setSelectedAnnotation}
              onDelete={removeAnnotation}
              onRefresh={refresh}
              loading={loading}
            />
          </div>

          <div className="lg:col-span-1">
            <StatusDistribution stats={stats} />
            
            <div className="card p-4">
              <h3 className="font-medium text-slate-700 mb-3">快速操作指南</h3>
              <div className="space-y-3 text-sm text-slate-600">
                <div className="flex items-start gap-2">
                  <span className="w-5 h-5 bg-primary-100 text-primary-600 rounded-full flex items-center justify-center text-xs font-medium flex-shrink-0">1</span>
                  <p>点击「导入会审清单」上传 Excel 文件或使用样例数据</p>
                </div>
                <div className="flex items-start gap-2">
                  <span className="w-5 h-5 bg-primary-100 text-primary-600 rounded-full flex items-center justify-center text-xs font-medium flex-shrink-0">2</span>
                  <p>在「问题区」修复缺少页码或专业错误的记录</p>
                </div>
                <div className="flex items-start gap-2">
                  <span className="w-5 h-5 bg-primary-100 text-primary-600 rounded-full flex items-center justify-center text-xs font-medium flex-shrink-0">3</span>
                  <p>点击「查看详情」添加回复、分派责任人、查看版本历史</p>
                </div>
                <div className="flex items-start gap-2">
                  <span className="w-5 h-5 bg-primary-100 text-primary-600 rounded-full flex items-center justify-center text-xs font-medium flex-shrink-0">4</span>
                  <p>点击「刷新数据」确认列表、详情、导出摘要数据一致</p>
                </div>
                <div className="flex items-start gap-2">
                  <span className="w-5 h-5 bg-green-100 text-green-600 rounded-full flex items-center justify-center text-xs font-medium flex-shrink-0">✓</span>
                  <p>刷新页面后所有数据保持不变，存储在浏览器本地 IndexedDB</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      {selectedAnnotation && (
        <DetailDrawer
          annotation={selectedAnnotation}
          onClose={() => setSelectedAnnotation(null)}
          onRefresh={refresh}
        />
      )}

      {showImportWizard && (
        <ImportWizard
          onClose={() => setShowImportWizard(false)}
          onSuccess={handleImportSuccess}
        />
      )}

      {showHelp && (
        <div className="modal-backdrop" onClick={() => setShowHelp(false)}>
          <div className="modal-panel" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
              <h3 className="text-lg font-semibold text-slate-800">使用帮助</h3>
              <button
                onClick={() => setShowHelp(false)}
                className="p-2 hover:bg-slate-100 rounded-lg"
              >
                ×
              </button>
            </div>
            <div className="p-6 max-h-[70vh] overflow-y-auto scrollbar-thin">
              <div className="space-y-6">
                <div>
                  <h4 className="font-medium text-slate-800 mb-2">项目简介</h4>
                  <p className="text-slate-600 text-sm">
                    「图纸会审批注追踪板」用于管理设计会审后多专业批注意见的追踪。
                    解决设计经理在会审后面临的 PDF 截图零散、微信群意见混杂、Excel 清单不统一等问题，
                    确保每条意见都能追踪到责任人和回复状态。
                  </p>
                </div>

                <div>
                  <h4 className="font-medium text-slate-800 mb-2">核心功能</h4>
                  <ul className="text-sm text-slate-600 space-y-2">
                    <li className="flex items-start gap-2">
                      <span className="text-primary-600">•</span>
                      <strong>批注定位</strong>：按楼栋、专业、责任人、图纸页码多维度筛选
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary-600">•</span>
                      <strong>责任流转</strong>：分派责任人、记录回复历史、状态追踪
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary-600">•</span>
                      <strong>版本对比</strong>：查看批注的历史回复，追踪处理过程
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary-600">•</span>
                      <strong>异常隔离</strong>：缺少页码、专业错误的记录自动放入问题区
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary-600">•</span>
                      <strong>导出一致</strong>：Excel 清单、回复摘要、核对表三种格式导出
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary-600">•</span>
                      <strong>导入去重</strong>：重复文件或重复批注编号自动检测并跳过
                    </li>
                  </ul>
                </div>

                <div>
                  <h4 className="font-medium text-slate-800 mb-2">数据存储说明</h4>
                  <p className="text-slate-600 text-sm">
                    所有数据存储在浏览器本地的 IndexedDB 中，不会上传到任何服务器。
                    刷新页面后数据保持不变，清理浏览器数据会导致数据丢失。
                  </p>
                </div>

                <div>
                  <h4 className="font-medium text-slate-800 mb-2">验证流程</h4>
                  <ol className="text-sm text-slate-600 space-y-2 list-decimal list-inside">
                    <li>点击「导入会审清单」→「导入样例数据」</li>
                    <li>查看问题区的 3 条问题记录，尝试修复其中一条</li>
                    <li>点击任一条目的「查看详情」，添加一条回复</li>
                    <li>点击「刷新数据」，确认记录数和状态正确</li>
                    <li>点击「导出」→「验证数据一致性」，记录哈希值</li>
                    <li>按 F5 刷新页面，再次验证数据和哈希值</li>
                    <li>导出 Excel 和回复摘要，确认内容与列表一致</li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

async function getRepliesForAnnotations(annotations) {
  const allReplies = [];
  for (const annotation of annotations) {
    const replies = await getRepliesByAnnotationId(annotation.id);
    allReplies.push(...replies);
  }
  return allReplies;
}

function formatDate() {
  const now = new Date();
  return `${now.getFullYear()}${(now.getMonth() + 1).toString().padStart(2, '0')}${now.getDate().toString().padStart(2, '0')}`;
}

export default App;
