// change-impact-dashboard/src/components/ImportWizard.vue
<template>
  <Teleport to="body">
    <Transition name="fade">
      <div v-if="isOpen" class="modal-backdrop" @click.self="closeWizard">
        <div class="modal-panel">
          <div class="p-4 border-b border-slate-200 flex items-center justify-between">
            <h3 class="text-lg font-semibold text-slate-800 flex items-center gap-2">
              <Upload class="w-5 h-5 text-primary-600" />
              导入设计变更
            </h3>
            <button @click="closeWizard" class="p-2 hover:bg-slate-100 rounded-lg transition-colors">
              <X class="w-5 h-5 text-slate-500" />
            </button>
          </div>
          
          <div class="p-4">
            <div class="flex items-center justify-center mb-6">
              <div class="flex items-center">
                <div 
                  v-for="(step, index) in steps" 
                  :key="step.id"
                  class="flex items-center"
                >
                  <div 
                    :class="[
                      'w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium transition-colors',
                      currentStep === index + 1 
                        ? 'bg-primary-600 text-white' 
                        : currentStep > index + 1
                          ? 'bg-green-500 text-white'
                          : 'bg-slate-200 text-slate-500'
                    ]"
                  >
                    <Check v-if="currentStep > index + 1" class="w-4 h-4" />
                    <span v-else>{{ index + 1 }}</span>
                  </div>
                  <span 
                    :class="[
                      'ml-2 text-sm font-medium',
                      currentStep >= index + 1 ? 'text-slate-700' : 'text-slate-400'
                    ]"
                  >
                    {{ step.name }}
                  </span>
                  <div 
                    v-if="index < steps.length - 1"
                    :class="[
                      'w-16 h-0.5 mx-3',
                      currentStep > index + 1 ? 'bg-green-500' : 'bg-slate-200'
                    ]"
                  ></div>
                </div>
              </div>
            </div>
            
            <div v-if="currentStep === 1">
              <div class="text-center py-8">
                <FileUp class="w-16 h-16 text-slate-300 mx-auto mb-4" />
                <h4 class="text-base font-medium text-slate-700 mb-2">选择 Excel 文件</h4>
                <p class="text-sm text-slate-500 mb-6">
                  支持 .xlsx 格式，请确保文件格式正确
                </p>
                
                <div class="grid grid-cols-2 gap-3 max-w-md mx-auto mb-4">
                  <label class="cursor-pointer">
                    <div class="border-2 border-dashed border-slate-300 rounded-xl p-6 hover:border-primary-400 hover:bg-primary-50/50 transition-all">
                      <Upload class="w-8 h-8 text-slate-400 mx-auto mb-2" />
                      <div class="text-sm font-medium text-slate-700">选择文件</div>
                      <div class="text-xs text-slate-400 mt-1">点击上传</div>
                    </div>
                    <input 
                      type="file" 
                      ref="fileInput"
                      accept=".xlsx,.xls"
                      class="hidden"
                      @change="handleFileSelect"
                    />
                  </label>
                  
                  <div 
                    @click="importSampleData"
                    class="cursor-pointer border-2 border-dashed border-slate-300 rounded-xl p-6 hover:border-green-400 hover:bg-green-50/50 transition-all"
                  >
                    <Database class="w-8 h-8 text-slate-400 mx-auto mb-2" />
                    <div class="text-sm font-medium text-slate-700">导入样例数据</div>
                    <div class="text-xs text-slate-400 mt-1">快速体验</div>
                  </div>
                </div>
                
                <button 
                  @click="downloadTemplate"
                  class="text-sm text-primary-600 hover:text-primary-700 flex items-center gap-1 mx-auto"
                >
                  <Download class="w-4 h-4" />
                  下载导入模板
                </button>
              </div>
            </div>
            
            <div v-if="currentStep === 2">
              <h4 class="text-base font-medium text-slate-700 mb-4">确认导入数据</h4>
              
              <div v-if="previewData.length > 0" class="space-y-4">
                <div class="flex items-center justify-between p-3 bg-slate-50 rounded-lg">
                  <div class="text-sm text-slate-600">
                    共 <span class="font-semibold text-slate-700">{{ previewData.length }}</span> 条数据待导入
                  </div>
                  <div class="flex items-center gap-3 text-xs">
                    <span class="text-green-600 flex items-center gap-1">
                      <Check class="w-3 h-3" />
                      可导入 {{ importResult?.imported || 0 }}
                    </span>
                    <span v-if="importResult?.skipped > 0" class="text-amber-600 flex items-center gap-1">
                      <AlertCircle class="w-3 h-3" />
                      跳过 {{ importResult.skipped }}
                    </span>
                    <span v-if="importResult?.errors > 0" class="text-red-600 flex items-center gap-1">
                      <X class="w-3 h-3" />
                      错误 {{ importResult.errors }}
                    </span>
                  </div>
                </div>
                
                <div class="max-h-64 overflow-y-auto scrollbar-thin border border-slate-200 rounded-lg">
                  <table class="w-full text-sm">
                    <thead class="bg-slate-50 sticky top-0">
                      <tr>
                        <th class="px-3 py-2 text-left text-xs font-semibold text-slate-500">变更编号</th>
                        <th class="px-3 py-2 text-left text-xs font-semibold text-slate-500">标题</th>
                        <th class="px-3 py-2 text-left text-xs font-semibold text-slate-500">楼层</th>
                        <th class="px-3 py-2 text-left text-xs font-semibold text-slate-500">专业</th>
                        <th class="px-3 py-2 text-left text-xs font-semibold text-slate-500">状态</th>
                      </tr>
                    </thead>
                    <tbody class="divide-y divide-slate-100">
                      <tr 
                        v-for="(item, index) in previewData" 
                        :key="index"
                        class="hover:bg-slate-50"
                      >
                        <td class="px-3 py-2 font-mono text-xs">{{ item.changeNo }}</td>
                        <td class="px-3 py-2 max-w-xs truncate" :title="item.title">{{ item.title }}</td>
                        <td class="px-3 py-2">{{ getFloorName(item.floorId) }}</td>
                        <td class="px-3 py-2">{{ getMajorName(item.major) }}</td>
                        <td class="px-3 py-2">
                          <span v-if="importResult?.skippedItems?.find(s => s.changeNo === item.changeNo)" class="text-amber-600 text-xs">
                            重复，跳过
                          </span>
                          <span v-else-if="importResult?.errorItems?.find(e => e.includes(item.changeNo))" class="text-red-600 text-xs">
                            数据错误
                          </span>
                          <span v-else class="text-green-600 text-xs">可导入</span>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            
            <div v-if="currentStep === 3">
              <div class="text-center py-12">
                <div class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <Check class="w-8 h-8 text-green-600" />
                </div>
                <h4 class="text-lg font-semibold text-slate-800 mb-2">导入完成</h4>
                <p class="text-sm text-slate-500 mb-6">
                  成功导入 {{ importResult?.imported || 0 }} 条变更数据
                </p>
                
                <div v-if="importResult?.skipped > 0 || importResult?.errors > 0" class="max-w-md mx-auto space-y-2 text-left">
                  <div v-if="importResult?.skipped > 0" class="p-3 bg-amber-50 rounded-lg text-sm">
                    <div class="text-amber-700 font-medium mb-1">跳过 {{ importResult.skipped }} 条</div>
                    <div v-for="item in importResult.skippedItems" :key="item.changeNo" class="text-xs text-amber-600">
                      • {{ item.changeNo }} - {{ item.reason }}
                    </div>
                  </div>
                  <div v-if="importResult?.errors > 0" class="p-3 bg-red-50 rounded-lg text-sm">
                    <div class="text-red-700 font-medium mb-1">错误 {{ importResult.errors }} 条</div>
                    <div v-for="(error, index) in importResult.errorItems" :key="index" class="text-xs text-red-600">
                      • {{ error }}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <div class="p-4 border-t border-slate-200 flex justify-between">
            <button 
              v-if="currentStep > 1"
              @click="prevStep"
              class="btn-secondary"
            >
              上一步
            </button>
            <div v-else></div>
            
            <div class="flex gap-3">
              <button @click="closeWizard" class="btn-secondary">
                {{ currentStep === 3 ? '关闭' : '取消' }}
              </button>
              <button 
                v-if="currentStep < 3"
                @click="nextStep"
                :disabled="!canProceed"
                class="btn-primary"
              >
                {{ currentStep === 2 ? '确认导入' : '下一步' }}
              </button>
              <button 
                v-if="currentStep === 3"
                @click="closeWizard"
                class="btn-primary"
              >
                完成
              </button>
            </div>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup>
import { ref, computed, watch } from 'vue';
import { X, Upload, Check, FileUp, Database, Download, AlertCircle } from 'lucide-vue-next';
import { useChangeStore } from '../stores/changeStore';
import { FLOORS, MAJORS } from '../data/constants';
import { parseExcelFile, downloadImportTemplate } from '../utils/importExport';
import { importTemplate } from '../data/mockData';
import { v4 as uuidv4 } from 'uuid';

const props = defineProps({
  isOpen: Boolean
});

const emit = defineEmits(['close']);

const store = { change: useChangeStore() };

const steps = [
  { id: 1, name: '选择文件' },
  { id: 2, name: '预览确认' },
  { id: 3, name: '导入完成' }
];

const currentStep = ref(1);
const fileInput = ref(null);
const previewData = ref([]);
const importResult = ref(null);

const canProceed = computed(() => {
  if (currentStep.value === 1) return previewData.value.length > 0;
  if (currentStep.value === 2) return importResult.value?.imported > 0;
  return true;
});

const getFloorName = (id) => {
  const floor = FLOORS.find(f => f.id === id);
  return floor ? floor.name : id;
};

const getMajorName = (id) => {
  const major = MAJORS.find(m => m.id === id);
  return major ? major.name : id;
};

const closeWizard = () => {
  currentStep.value = 1;
  previewData.value = [];
  importResult.value = null;
  emit('close');
};

const prevStep = () => {
  if (currentStep.value > 1) {
    currentStep.value--;
  }
};

const nextStep = async () => {
  if (currentStep.value === 2) {
    const result = store.change.importChanges(previewData.value, true);
    importResult.value = result;
    currentStep.value = 3;
  } else if (currentStep.value < 3) {
    currentStep.value++;
  }
};

const handleFileSelect = async (event) => {
  const file = event.target.files?.[0];
  if (!file) return;
  
  try {
    const changes = await parseExcelFile(file);
    previewData.value = changes;
    
    const existingNos = new Set(store.change.changes.map(c => c.changeNo));
    const skipped = [];
    const errors = [];
    
    changes.forEach((change, index) => {
      if (existingNos.has(change.changeNo)) {
        skipped.push({ changeNo: change.changeNo, reason: '变更编号已存在' });
      }
      if (!change.floorId) {
        errors.push(`变更 ${change.changeNo} 缺少楼层信息`);
      }
    });
    
    importResult.value = {
      imported: changes.length - skipped.length - errors.length,
      skipped: skipped.length,
      errors: errors.length,
      skippedItems: skipped,
      errorItems: errors
    };
    
    currentStep.value = 2;
  } catch (error) {
    alert('文件解析失败：' + error.message);
  }
  
  event.target.value = '';
};

const importSampleData = () => {
  const sampleChanges = importTemplate.map(row => {
    const affectedAreas = typeof row.affectedAreas === 'string' 
      ? row.affectedAreas.split(/[,，、]/).map(s => s.trim()).filter(Boolean)
      : [];
      
    return {
      id: uuidv4(),
      changeNo: row.changeNo,
      version: 1,
      title: row.title,
      description: row.description,
      source: row.source || 'design_letter',
      sourceRef: row.sourceRef || '',
      dateIssued: row.dateIssued,
      dateReceived: row.dateReceived,
      floorId: row.floorId,
      major: row.major,
      affectedAreas,
      constructionStatus: row.constructionStatus || 'drawing',
      constructionProgress: row.constructionProgress || '',
      impactLevel: row.impactLevel || 'medium',
      costImpact: Number(row.costImpact) || 0,
      scheduleImpact: Number(row.scheduleImpact) || 0,
      processImpact: row.processImpact || '',
      responsiblePerson: row.responsiblePerson || null,
      status: row.status || 'pending',
      attachments: [],
      remarks: row.remarks || '',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      history: [
        {
          id: uuidv4(),
          action: 'import',
          timestamp: new Date().toISOString(),
          operator: 'sun',
          oldValue: null,
          newValue: { status: 'pending', imported: true },
          reason: '导入样例数据'
        }
      ]
    };
  });
  
  previewData.value = sampleChanges;
  
  const existingNos = new Set(store.change.changes.map(c => c.changeNo));
  const skipped = [];
  const errors = [];
  
  sampleChanges.forEach(change => {
    if (existingNos.has(change.changeNo)) {
      skipped.push({ changeNo: change.changeNo, reason: '变更编号已存在' });
    }
  });
  
  importResult.value = {
    imported: sampleChanges.length - skipped.length,
    skipped: skipped.length,
    errors: 0,
    skippedItems: skipped,
    errorItems: errors
  };
  
  currentStep.value = 2;
};

const downloadTemplate = () => {
  downloadImportTemplate();
};

watch(() => props.isOpen, (newVal) => {
  if (!newVal) {
    currentStep.value = 1;
    previewData.value = [];
    importResult.value = null;
  }
});
</script>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// annotation-tracker/src/components/ImportWizard.jsx
import { useState } from 'react';
import { X, Upload, FileSpreadsheet, CheckCircle, AlertTriangle, Download, Info } from 'lucide-react';
import { parseExcelFile, importExcelFile, downloadImportTemplate } from '../utils/import';
import { excelImportTemplate } from '../data/mockData';
import { importAnnotations } from '../db/operations';

export function ImportWizard({ onClose, onSuccess }) {
  const [step, setStep] = useState(1);
  const [file, setFile] = useState(null);
  const [parsedData, setParsedData] = useState(null);
  const [importing, setImporting] = useState(false);
  const [importResult, setImportResult] = useState(null);
  const [error, setError] = useState(null);

  const handleFileSelect = async (e) => {
    const selectedFile = e.target.files?.[0];
    if (!selectedFile) return;

    if (!selectedFile.name.endsWith('.xlsx') && !selectedFile.name.endsWith('.xls')) {
      setError('请选择 Excel 文件（.xlsx 或 .xls 格式）');
      return;
    }

    setFile(selectedFile);
    setError(null);

    try {
      const parsed = await parseExcelFile(selectedFile);
      setParsedData(parsed);
      setStep(2);
    } catch (err) {
      setError(err.message);
    }
  };

  const handleImport = async () => {
    setImporting(true);
    setError(null);

    try {
      const result = await importExcelFile(file);
      setImportResult(result.importResult);
      setStep(3);
      
      if (result.importResult.success) {
        setTimeout(() => {
          onSuccess();
        }, 1500);
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setImporting(false);
    }
  };

  const handleImportSample = async () => {
    setImporting(true);
    try {
      const result = await importAnnotations(excelImportTemplate, '样例数据导入');
      setImportResult(result);
      setStep(3);
      
      if (result.success) {
        setTimeout(() => {
          onSuccess();
        }, 1500);
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setImporting(false);
    }
  };

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-panel" onClick={e => e.stopPropagation()}>
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
          <div className="flex items-center gap-3">
            <FileSpreadsheet className="w-6 h-6 text-primary-600" />
            <h3 className="text-lg font-semibold text-slate-800">
              导入会审清单
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-slate-500" />
          </button>
        </div>

        <div className="px-6 py-4 border-b border-slate-100 bg-slate-50">
          <div className="flex items-center gap-4">
            {[1, 2, 3].map((s) => (
              <div key={s} className="flex items-center">
                <div
                  className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium ${
                    step === s
                      ? 'bg-primary-600 text-white'
                      : step > s
                      ? 'bg-green-500 text-white'
                      : 'bg-slate-200 text-slate-500'
                  }`}
                >
                  {step > s ? <CheckCircle className="w-5 h-5" /> : s}
                </div>
                <span
                  className={`ml-2 text-sm ${
                    step >= s ? 'text-slate-700 font-medium' : 'text-slate-400'
                  }`}
                >
                  {s === 1 ? '选择文件' : s === 2 ? '预览确认' : '导入完成'}
                </span>
                {s < 3 && <div className="w-12 h-0.5 bg-slate-200 mx-4" />}
              </div>
            ))}
          </div>
        </div>

        <div className="p-6 max-h-[60vh] overflow-y-auto scrollbar-thin">
          {error && (
            <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-lg flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-red-700 font-medium">导入失败</p>
                <p className="text-red-600 text-sm">{error}</p>
              </div>
            </div>
          )}

          {step === 1 && (
            <div>
              <div className="mb-6">
                <div className="flex items-center justify-between mb-3">
                  <p className="text-sm text-slate-600">
                    支持 .xlsx 和 .xls 格式的 Excel 文件
                  </p>
                  <button
                    onClick={downloadImportTemplate}
                    className="text-sm text-primary-600 hover:text-primary-700 flex items-center gap-1"
                  >
                    <Download className="w-4 h-4" />
                    下载导入模板
                  </button>
                </div>

                <label className="block">
                  <div className="border-2 border-dashed border-slate-300 rounded-xl p-12 text-center cursor-pointer hover:border-primary-500 hover:bg-primary-50/30 transition-colors">
                    <Upload className="w-12 h-12 text-slate-400 mx-auto mb-4" />
                    <p className="text-slate-600 mb-2">点击或拖拽文件到此处</p>
                    <p className="text-sm text-slate-400">
                      选择要导入的会审清单 Excel 文件
                    </p>
                  </div>
                  <input
                    type="file"
                    accept=".xlsx,.xls"
                    className="hidden"
                    onChange={handleFileSelect}
                  />
                </label>
              </div>

              <div className="mt-8 pt-6 border-t border-slate-200">
                <div className="flex items-center justify-between">
                  <div className="flex items-start gap-2 text-sm text-slate-500">
                    <Info className="w-4 h-4 flex-shrink-0 mt-0.5" />
                    <p>
                      不想准备文件？可以直接导入系统提供的样例数据体验功能
                    </p>
                  </div>
                  <button
                    onClick={handleImportSample}
                    disabled={importing}
                    className="btn-secondary"
                  >
                    导入样例数据
                  </button>
                </div>
              </div>
            </div>
          )}

          {step === 2 && parsedData && (
            <div>
              <div className="mb-4">
                <h4 className="font-medium text-slate-700 mb-2">文件信息</h4>
                <div className="grid grid-cols-3 gap-4">
                  <div className="bg-slate-50 rounded-lg p-3">
                    <p className="text-sm text-slate-500">文件名</p>
                    <p className="font-medium text-slate-800 truncate" title={parsedData.fileName}>
                      {parsedData.fileName}
                    </p>
                  </div>
                  <div className="bg-slate-50 rounded-lg p-3">
                    <p className="text-sm text-slate-500">记录数</p>
                    <p className="font-medium text-slate-800">{parsedData.rowCount} 条</p>
                  </div>
                  <div className="bg-slate-50 rounded-lg p-3">
                    <p className="text-sm text-slate-500">列数</p>
                    <p className="font-medium text-slate-800">{parsedData.columns.length} 列</p>
                  </div>
                </div>
              </div>

              <div className="mb-4">
                <h4 className="font-medium text-slate-700 mb-2">数据预览（前 5 条）</h4>
                <div className="overflow-x-auto border border-slate-200 rounded-lg">
                  <table className="w-full text-sm">
                    <thead className="bg-slate-50">
                      <tr>
                        <th className="px-3 py-2 text-left text-xs font-medium text-slate-500">行号</th>
                        {parsedData.columns.map(col => (
                          <th key={col} className="px-3 py-2 text-left text-xs font-medium text-slate-500">
                            {col}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {parsedData.preview.map((row, idx) => (
                        <tr key={idx} className="border-t border-slate-100">
                          <td className="px-3 py-2 text-slate-500">{idx + 1}</td>
                          {parsedData.columns.map(col => (
                            <td key={col} className="px-3 py-2 text-slate-700">
                              {row[col]?.toString() || '-'}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <div className="flex items-start gap-3">
                  <Info className="w-5 h-5 text-blue-500 flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="text-blue-700 font-medium mb-1">导入规则说明</p>
                    <ul className="text-sm text-blue-600 space-y-1">
                      <li>• 系统会自动检测重复的批注编号，重复记录将被跳过</li>
                      <li>• 相同内容的文件只能导入一次，避免重复数据</li>
                      <li>• 缺少页码或专业名称错误的记录会被放到问题区</li>
                      <li>• 导入后可以在列表中编辑和分派责任人</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          )}

          {step === 3 && importResult && (
            <div className="text-center py-8">
              {importResult.success ? (
                <>
                  <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                    <CheckCircle className="w-8 h-8 text-green-600" />
                  </div>
                  <h4 className="text-xl font-semibold text-slate-800 mb-2">导入成功</h4>
                  <p className="text-slate-600 mb-6">
                    共 {importResult.total} 条记录
                  </p>
                  <div className="grid grid-cols-3 gap-4 max-w-md mx-auto">
                    <div className="bg-green-50 rounded-lg p-4">
                      <p className="text-2xl font-bold text-green-600">{importResult.imported}</p>
                      <p className="text-sm text-green-700">成功导入</p>
                    </div>
                    <div className="bg-amber-50 rounded-lg p-4">
                      <p className="text-2xl font-bold text-amber-600">{importResult.errors}</p>
                      <p className="text-sm text-amber-700">待处理问题</p>
                    </div>
                    <div className="bg-slate-50 rounded-lg p-4">
                      <p className="text-2xl font-bold text-slate-600">{importResult.skipped}</p>
                      <p className="text-sm text-slate-700">重复跳过</p>
                    </div>
                  </div>
                  {importResult.errorDetails.length > 0 && (
                    <div className="mt-6 text-left max-w-md mx-auto">
                      <p className="text-sm font-medium text-slate-600 mb-2">详细信息：</p>
                      <ul className="text-sm text-slate-500 space-y-1">
                        {importResult.errorDetails.slice(0, 3).map((err, idx) => (
                          <li key={idx}>• 第 {err.row} 行 {err.annotationNo}：{err.reason}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </>
              ) : (
                <>
                  <div className="w-16 h-16 bg-amber-100 rounded-full flex items-center justify-center mx-auto mb-4">
                    <AlertTriangle className="w-8 h-8 text-amber-600" />
                  </div>
                  <h4 className="text-xl font-semibold text-slate-800 mb-2">导入被阻止</h4>
                  <p className="text-slate-600">{importResult.message}</p>
                </>
              )}
            </div>
          )}
        </div>

        <div className="px-6 py-4 border-t border-slate-200 flex justify-between">
          {step === 1 ? (
            <button onClick={onClose} className="btn-secondary">
              取消
            </button>
          ) : (
            <button
              onClick={() => setStep(s => s - 1)}
              className="btn-secondary"
              disabled={step === 3 || importing}
            >
              上一步
            </button>
          )}
          
          <div className="flex gap-3">
            {step < 3 && (
              <button
                onClick={handleImport}
                className="btn-primary"
                disabled={!parsedData || importing}
              >
                {importing ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2"></div>
                    导入中...
                  </>
                ) : (
                  '确认导入'
                )}
              </button>
            )}
            {step === 3 && (
              <button onClick={onClose} className="btn-primary">
                完成
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
