// rebar-diff-board/src/components/FilterPanel.vue
<template>
  <div class="bg-white rounded-lg border border-gray-200 shadow-sm p-4 space-y-4">
    <div class="flex items-center justify-between">
      <div class="flex items-center gap-2">
        <Filter class="w-5 h-5 text-rebar-orange" />
        <h3 class="font-semibold text-gray-900">筛选条件</h3>
        <span class="text-xs text-gray-500">({{ filteredCount }} 条)</span>
      </div>
      <button
        v-if="hasActiveFilters"
        @click="$emit('reset')"
        class="text-xs text-rebar-orange hover:text-rebar-orange-dark flex items-center gap-1"
      >
        <X class="w-3.5 h-3.5" />
        重置
      </button>
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">规格关键词</label>
      <input
        type="text"
        :value="filter.specKeyword"
        @input="$emit('update:filter', { specKeyword: ($event.target as HTMLInputElement).value })"
        placeholder="如：HRB400、Φ20..."
        class="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-rebar-orange focus:border-transparent"
      />
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">状态</label>
      <div class="flex flex-wrap gap-2">
        <button
          v-for="status in statusOptions"
          :key="status.value"
          @click="$emit('toggle-status', status.value)"
          :class="[
            'px-3 py-1.5 rounded-full text-xs font-medium transition-colors',
            filter.status.includes(status.value)
              ? 'text-white'
              : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
          ]"
          :style="{ backgroundColor: filter.status.includes(status.value) ? status.color : undefined }"
        >
          {{ status.label }}
        </button>
      </div>
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">楼栋</label>
      <div class="flex flex-wrap gap-2 max-h-24 overflow-y-auto">
        <button
          v-for="b in buildings"
          :key="b"
          @click="$emit('toggle-building', b)"
          :class="[
            'px-3 py-1.5 rounded-full text-xs font-medium transition-colors',
            filter.building.includes(b)
              ? 'bg-rebar-blue text-white'
              : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
          ]"
        >
          {{ b }}
        </button>
      </div>
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">差异数量范围</label>
      <div class="flex items-center gap-2">
        <input
          type="number"
          :value="filter.diffMin ?? ''"
          @input="$emit('update:filter', { diffMin: ($event.target as HTMLInputElement).value ? Number(($event.target as HTMLInputElement).value) : null })"
          placeholder="最小"
          class="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-rebar-orange focus:border-transparent"
        />
        <span class="text-gray-400">~</span>
        <input
          type="number"
          :value="filter.diffMax ?? ''"
          @input="$emit('update:filter', { diffMax: ($event.target as HTMLInputElement).value ? Number(($event.target as HTMLInputElement).value) : null })"
          placeholder="最大"
          class="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-rebar-orange focus:border-transparent"
        />
      </div>
    </div>

    <div class="flex items-center gap-2">
      <input
        type="checkbox"
        :checked="filter.onlyUnresolved"
        @change="$emit('update:filter', { onlyUnresolved: ($event.target as HTMLInputElement).checked })"
        id="onlyUnresolved"
        class="w-4 h-4 text-rebar-orange focus:ring-rebar-orange"
      />
      <label for="onlyUnresolved" class="text-sm text-gray-700">仅显示未处理</label>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Filter, X } from 'lucide-vue-next'
import type { FilterState, DiffStatus } from '@/types'

defineProps<{
  filter: FilterState
  buildings: string[]
  filteredCount: number
  hasActiveFilters: boolean
}>()

defineEmits<{
  'update:filter': [filter: Partial<FilterState>]
  'toggle-building': [building: string]
  'toggle-status': [status: DiffStatus]
  'reset': []
}>()

const statusOptions = [
  { value: 'shortage' as DiffStatus, label: '少料', color: '#DC2626' },
  { value: 'surplus' as DiffStatus, label: '多料', color: '#059669' },
  { value: 'matched' as DiffStatus, label: '一致', color: '#6B7280' },
  { value: 'pending' as DiffStatus, label: '待确认', color: '#D97706' },
  { value: 'bad' as DiffStatus, label: '坏行', color: '#7C3AED' }
]
</script>

// gyf607130/src/components/FilterPanel.tsx
import { Search, Filter, X } from 'lucide-react';
import { useForecastStore } from '../store/useForecastStore';
import { statusLabels } from '../data/mockData';

export const FilterPanel = () => {
  const { filters, setFilters, resetFilters, getFilteredRecords } = useForecastStore();
  const filteredCount = getFilteredRecords().length;

  const hasActiveFilters = filters.deviceNo || filters.status || 
    filters.isAbnormal !== null || filters.hasStatusConflict !== null;

  return (
    <div className="bg-white border-b border-slate-200 px-6 py-4">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <Filter size={16} className="text-slate-500" />
          <span className="text-sm font-medium text-slate-700">筛选条件</span>
          <span className="text-xs text-slate-400 ml-1">
            (共 {filteredCount} 条记录)
          </span>
        </div>
        {hasActiveFilters && (
          <button
            onClick={resetFilters}
            className="flex items-center gap-1 text-xs text-slate-500 hover:text-slate-700 transition-colors"
          >
            <X size={14} />
            清除筛选
          </button>
        )}
      </div>

      <div className="flex flex-wrap items-center gap-4">
        <div className="flex items-center gap-2">
          <Search size={14} className="text-slate-400" />
          <input
            type="text"
            placeholder="设备编号..."
            value={filters.deviceNo}
            onChange={(e) => setFilters({ deviceNo: e.target.value })}
            className="w-36 px-3 py-1.5 border border-slate-300 rounded text-sm focus:outline-none focus:border-blue-500 transition-colors"
          />
        </div>

        <div className="flex items-center gap-2">
          <span className="text-sm text-slate-600">状态:</span>
          <select
            value={filters.status}
            onChange={(e) => setFilters({ status: e.target.value })}
            className="px-3 py-1.5 border border-slate-300 rounded text-sm focus:outline-none focus:border-blue-500 transition-colors bg-white"
          >
            <option value="">全部</option>
            {Object.entries(statusLabels).map(([value, label]) => (
              <option key={value} value={value}>{label}</option>
            ))}
          </select>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-sm text-slate-600">异常标记:</span>
          <select
            value={filters.isAbnormal === null ? '' : String(filters.isAbnormal)}
            onChange={(e) => {
              const val = e.target.value;
              setFilters({ isAbnormal: val === '' ? null : val === 'true' });
            }}
            className="px-3 py-1.5 border border-slate-300 rounded text-sm focus:outline-none focus:border-blue-500 transition-colors bg-white"
          >
            <option value="">全部</option>
            <option value="true">异常</option>
            <option value="false">正常</option>
          </select>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-sm text-slate-600">状态冲突:</span>
          <select
            value={filters.hasStatusConflict === null ? '' : String(filters.hasStatusConflict)}
            onChange={(e) => {
              const val = e.target.value;
              setFilters({ hasStatusConflict: val === '' ? null : val === 'true' });
            }}
            className="px-3 py-1.5 border border-slate-300 rounded text-sm focus:outline-none focus:border-blue-500 transition-colors bg-white"
          >
            <option value="">全部</option>
            <option value="true">有冲突</option>
            <option value="false">无冲突</option>
          </select>
        </div>

        <div className="ml-auto flex items-center gap-2 text-xs">
          <span className="inline-flex items-center gap-1 px-2 py-1 bg-orange-50 text-orange-700 rounded">
            <span className="w-2 h-2 bg-orange-500 rounded-full" />
            客服回访异常
          </span>
          <span className="inline-flex items-center gap-1 px-2 py-1 bg-red-50 text-red-700 rounded">
            <span className="w-2 h-2 bg-red-500 rounded-full" />
            多人修改冲突
          </span>
          <span className="inline-flex items-center gap-1 px-2 py-1 bg-blue-50 text-blue-700 rounded">
            <span className="w-2 h-2 bg-blue-500 rounded-full" />
            手工补录修正
          </span>
        </div>
      </div>
    </div>
  );
};
