// gyf607012/src/components/Modal.tsx
import { X } from "lucide-react";
import { useEffect, type ReactNode } from "react";

interface Props {
  open: boolean;
  title: string;
  onClose: () => void;
  children: ReactNode;
  width?: string;
}

export default function Modal({ open, title, onClose, children, width = "max-w-lg" }: Props) {
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && onClose();
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center animate-fade-in" onClick={onClose}>
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" />
      <div
        className={`relative ${width} w-full mx-4 bg-white rounded-2xl shadow-xl animate-slide-up`}
        onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
          <h3 className="font-serif text-lg font-semibold text-gray-800">{title}</h3>
          <button
            onClick={onClose}
            className="p-1.5 -mr-2 text-gray-400 rounded-lg hover:bg-gray-50 hover:text-gray-600 transition-colors">
            <X size={18} />
          </button>
        </div>
        <div className="px-6 py-5">{children}</div>
      </div>
    </div>
  );
}

// src/lib/components/Modal.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { X } from 'lucide-svelte';

	export let show = false;
	export let title = '';
	export let closeOnOverlay = true;
	export let closeOnEsc = true;

	function handleOverlayClick(e: MouseEvent) {
		const target = e.target as HTMLElement;
		if (closeOnOverlay && target.classList.contains('modal-overlay')) {
			show = false;
		}
	}

	function handleKeyDown(e: KeyboardEvent) {
		if (closeOnEsc && e.key === 'Escape') {
			show = false;
		}
	}

	onMount(() => {
		document.addEventListener('keydown', handleKeyDown);
	});

	onDestroy(() => {
		document.removeEventListener('keydown', handleKeyDown);
	});
</script>

{#if show}
	<div
		class="modal-overlay fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
		on:click={handleOverlayClick}
	>
		<div class="modal-content bg-white rounded-lg shadow-xl max-w-lg w-full max-h-[90vh] overflow-hidden animate-fade-in">
			{#if title}
				<div class="flex items-center justify-between p-4 border-b border-gray-200">
					<h3 class="text-lg font-semibold text-construction-gray-dark">{title}</h3>
					<button
						on:click={() => (show = false)}
						class="p-1 hover:bg-gray-100 rounded transition-colors"
						aria-label="关闭"
					>
						<X class="w-5 h-5 text-construction-gray" />
					</button>
				</div>
			{/if}
			<div class="p-4 overflow-y-auto max-h-[calc(90vh-80px)]">
				<slot />
			</div>
		</div>
	</div>
{/if}
