// gyf607034/src/components/Modal.tsx
import { X } from 'lucide-react';
import { type ReactNode, useEffect } from 'react';

interface Props {
  open: boolean;
  onClose: () => void;
  title: string;
  subtitle?: string;
  children: ReactNode;
  width?: string;
}

export function Modal({
  open,
  onClose,
  title,
  subtitle,
  children,
  width = 'max-w-lg',
}: Props) {
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-start md:items-center justify-center p-4 bg-ink-900/50 animate-fade-in">
      <div
        className={`w-full ${width} card shadow-pop animate-slide-up max-h-[90vh] flex flex-col`}
      >
        <div className="flex items-start justify-between px-5 py-4 border-b border-paper-200">
          <div>
            <h3 className="font-serif text-base font-semibold text-ink-800">
              {title}
            </h3>
            {subtitle && (
              <p className="text-xs text-ink-500 mt-0.5">{subtitle}</p>
            )}
          </div>
          <button
            onClick={onClose}
            className="text-ink-400 hover:text-ink-700 p-1"
            aria-label="关闭"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
        <div className="p-5 overflow-y-auto">{children}</div>
      </div>
    </div>
  );
}

// src/lib/components/Modal.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { X } from 'lucide-svelte';

	export let show = false;
	export let title = '';
	export let closeOnOverlay = true;
	export let closeOnEsc = true;

	function handleOverlayClick(e: MouseEvent) {
		const target = e.target as HTMLElement;
		if (closeOnOverlay && target.classList.contains('modal-overlay')) {
			show = false;
		}
	}

	function handleKeyDown(e: KeyboardEvent) {
		if (closeOnEsc && e.key === 'Escape') {
			show = false;
		}
	}

	onMount(() => {
		document.addEventListener('keydown', handleKeyDown);
	});

	onDestroy(() => {
		document.removeEventListener('keydown', handleKeyDown);
	});
</script>

{#if show}
	<div
		class="modal-overlay fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
		on:click={handleOverlayClick}
	>
		<div class="modal-content bg-white rounded-lg shadow-xl max-w-lg w-full max-h-[90vh] overflow-hidden animate-fade-in">
			{#if title}
				<div class="flex items-center justify-between p-4 border-b border-gray-200">
					<h3 class="text-lg font-semibold text-construction-gray-dark">{title}</h3>
					<button
						on:click={() => (show = false)}
						class="p-1 hover:bg-gray-100 rounded transition-colors"
						aria-label="关闭"
					>
						<X class="w-5 h-5 text-construction-gray" />
					</button>
				</div>
			{/if}
			<div class="p-4 overflow-y-auto max-h-[calc(90vh-80px)]">
				<slot />
			</div>
		</div>
	</div>
{/if}
