// gyf607011/src/components/Modal.tsx
import { useEffect } from 'react';
import { X } from 'lucide-react';

interface ModalProps {
  open: boolean;
  onClose: () => void;
  title: string;
  children: React.ReactNode;
  width?: string;
}

export default function Modal({ open, onClose, title, children, width = 'max-w-lg' }: ModalProps) {
  useEffect(() => {
    if (open) {
      document.body.style.overflow = 'hidden';
      return () => {
        document.body.style.overflow = '';
      };
    }
  }, [open]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 animate-dissolve">
      <div className="absolute inset-0 bg-medical-900/40 backdrop-blur-sm" onClick={onClose} />
      <div
        className={`relative bg-white rounded-2xl shadow-card w-full ${width} max-h-[90vh] flex flex-col animate-fade-in-up`}
      >
        <div className="flex items-center justify-between px-6 py-4 border-b border-medical-100">
          <h3 className="font-serif text-lg font-semibold text-medical-800">{title}</h3>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-lg text-medical-500 hover:bg-medical-50 hover:text-medical-700 flex items-center justify-center transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
        <div className="flex-1 overflow-y-auto px-6 py-5">{children}</div>
      </div>
    </div>
  );
}

// src/lib/components/Modal.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { X } from 'lucide-svelte';

	export let show = false;
	export let title = '';
	export let closeOnOverlay = true;
	export let closeOnEsc = true;

	function handleOverlayClick(e: MouseEvent) {
		const target = e.target as HTMLElement;
		if (closeOnOverlay && target.classList.contains('modal-overlay')) {
			show = false;
		}
	}

	function handleKeyDown(e: KeyboardEvent) {
		if (closeOnEsc && e.key === 'Escape') {
			show = false;
		}
	}

	onMount(() => {
		document.addEventListener('keydown', handleKeyDown);
	});

	onDestroy(() => {
		document.removeEventListener('keydown', handleKeyDown);
	});
</script>

{#if show}
	<div
		class="modal-overlay fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
		on:click={handleOverlayClick}
	>
		<div class="modal-content bg-white rounded-lg shadow-xl max-w-lg w-full max-h-[90vh] overflow-hidden animate-fade-in">
			{#if title}
				<div class="flex items-center justify-between p-4 border-b border-gray-200">
					<h3 class="text-lg font-semibold text-construction-gray-dark">{title}</h3>
					<button
						on:click={() => (show = false)}
						class="p-1 hover:bg-gray-100 rounded transition-colors"
						aria-label="关闭"
					>
						<X class="w-5 h-5 text-construction-gray" />
					</button>
				</div>
			{/if}
			<div class="p-4 overflow-y-auto max-h-[calc(90vh-80px)]">
				<slot />
			</div>
		</div>
	</div>
{/if}
