// gyf607010/src/components/Toast.tsx
import { useEffect, useState } from 'react';
import { AlertCircle, CheckCircle2, X } from 'lucide-react';

export type ToastType = 'success' | 'error' | 'info';

interface Toast {
  id: number;
  type: ToastType;
  message: string;
}

let listeners: Array<(t: Toast) => void> = [];
let idSeq = 1;

export function showToast(message: string, type: ToastType = 'success') {
  const toast: Toast = { id: idSeq++, type, message };
  listeners.forEach((l) => l(toast));
}

export function ToastHost() {
  const [toasts, setToasts] = useState<Toast[]>([]);

  useEffect(() => {
    const handler = (t: Toast) => {
      setToasts((prev) => [...prev, t]);
      setTimeout(() => {
        setToasts((prev) => prev.filter((x) => x.id !== t.id));
      }, 3500);
    };
    listeners.push(handler);
    return () => {
      listeners = listeners.filter((l) => l !== handler);
    };
  }, []);

  return (
    <div className="fixed top-20 right-6 z-50 flex flex-col gap-2">
      {toasts.map((t) => (
        <div
          key={t.id}
          className={`animate-fade-up shadow-lg rounded-xl px-4 py-3 flex items-center gap-3 min-w-[240px] ${
            t.type === 'success'
              ? 'bg-emerald-50 text-emerald-800 ring-1 ring-emerald-200'
              : t.type === 'error'
              ? 'bg-rose-50 text-rose-800 ring-1 ring-rose-200'
              : 'bg-brand-50 text-brand-800 ring-1 ring-brand-200'
          }`}
        >
          {t.type === 'success' ? (
            <CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0" />
          ) : (
            <AlertCircle className="w-5 h-5 text-rose-500 shrink-0" />
          )}
          <span className="text-sm flex-1">{t.message}</span>
          <button
            onClick={() => setToasts((prev) => prev.filter((x) => x.id !== t.id))}
            className="text-slate-400 hover:text-slate-600"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      ))}
    </div>
  );
}

// src/lib/components/Toast.svelte
<script lang="ts">
	import { onDestroy } from 'svelte';
	import { createEventDispatcher } from 'svelte';
	import { CheckCircle, XCircle, AlertTriangle, Info, X } from 'lucide-svelte';
	import type { ToastType, ToastItem } from '$lib/types';

	export let toasts: ToastItem[] = [];

	const dispatch = createEventDispatcher<{ update: ToastItem[] }>();

	const icons: Record<ToastType, typeof CheckCircle> = {
		success: CheckCircle,
		error: XCircle,
		warning: AlertTriangle,
		info: Info
	};

	function removeToast(id: string) {
		toasts = toasts.filter((t) => t.id !== id);
		dispatch('update', toasts);
	}

	function autoRemove(node: HTMLElement, toast: ToastItem) {
		if (toast.duration !== 0) {
			const timeout = setTimeout(() => {
				removeToast(toast.id);
			}, toast.duration || 3000);
			return {
				destroy() {
					clearTimeout(timeout);
				}
			};
		}
		return { destroy() {} };
	}
</script>

<div class="fixed top-4 right-4 z-50 flex flex-col gap-2 max-w-sm">
	{#each toasts as toast (toast.id)}
		<div
			class="toast toast-{toast.type} animate-slide-up"
			role="alert"
			use:autoRemove={toast}
		>
			<svelte:component this={icons[toast.type]} class="w-5 h-5 flex-shrink-0" />
			<p class="flex-1 text-sm">{toast.message}</p>
			<button
				on:click={() => removeToast(toast.id)}
				class="p-1 hover:bg-white hover:bg-opacity-20 rounded transition-colors"
				aria-label="关闭"
			>
				<X class="w-4 h-4" />
			</button>
		</div>
	{/each}
</div>
