// annotation-tracker/src/components/FilterPanel.jsx
import { Search, Filter, X, Building2, Users, FileText, Layers } from 'lucide-react';
import { BUILDINGS, MAJORS, ASSIGNEES, ANNOTATION_STATUS, ANNOTATION_STATUS_LABELS } from '../db';

export function FilterPanel({ filters, updateFilter, clearFilters }) {
  const hasActiveFilters = Object.values(filters).some(v => v !== '' && v !== undefined);
  
  return (
    <div className="card p-4 mb-6">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2 text-slate-700">
          <Filter className="w-5 h-5" />
          <span className="font-medium">筛选条件</span>
        </div>
        {hasActiveFilters && (
          <button
            onClick={clearFilters}
            className="text-sm text-slate-500 hover:text-slate-700 flex items-center gap-1"
          >
            <X className="w-4 h-4" />
            清除筛选
          </button>
        )}
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4">
        <div>
          <label className="block text-sm font-medium text-slate-600 mb-1 flex items-center gap-1">
            <Search className="w-4 h-4" />
            关键词搜索
          </label>
          <input
            type="text"
            className="input"
            placeholder="批注编号/内容..."
            value={filters.keyword}
            onChange={(e) => updateFilter('keyword', e.target.value)}
          />
        </div>
        
        <div>
          <label className="block text-sm font-medium text-slate-600 mb-1 flex items-center gap-1">
            <Building2 className="w-4 h-4" />
            楼栋
          </label>
          <select
            className="select"
            value={filters.building}
            onChange={(e) => updateFilter('building', e.target.value)}
          >
            <option value="">全部楼栋</option>
            {BUILDINGS.map(b => (
              <option key={b} value={b}>{b}</option>
            ))}
          </select>
        </div>
        
        <div>
          <label className="block text-sm font-medium text-slate-600 mb-1 flex items-center gap-1">
            <Layers className="w-4 h-4" />
            专业
          </label>
          <select
            className="select"
            value={filters.major}
            onChange={(e) => updateFilter('major', e.target.value)}
          >
            <option value="">全部专业</option>
            {MAJORS.map(m => (
              <option key={m} value={m}>{m}</option>
            ))}
          </select>
        </div>
        
        <div>
          <label className="block text-sm font-medium text-slate-600 mb-1 flex items-center gap-1">
            <Users className="w-4 h-4" />
            责任人
          </label>
          <select
            className="select"
            value={filters.assignee}
            onChange={(e) => updateFilter('assignee', e.target.value)}
          >
            <option value="">全部责任人</option>
            {ASSIGNEES.map(a => (
              <option key={a} value={a}>{a}</option>
            ))}
          </select>
        </div>
        
        <div>
          <label className="block text-sm font-medium text-slate-600 mb-1 flex items-center gap-1">
            <FileText className="w-4 h-4" />
            处理状态
          </label>
          <select
            className="select"
            value={filters.status}
            onChange={(e) => updateFilter('status', e.target.value)}
          >
            <option value="">全部状态</option>
            {Object.entries(ANNOTATION_STATUS).map(([key, value]) => (
              <option key={value} value={value}>
                {ANNOTATION_STATUS_LABELS[value]}
              </option>
            ))}
          </select>
        </div>
        
        <div>
          <label className="block text-sm font-medium text-slate-600 mb-1">
            图纸页码
          </label>
          <input
            type="text"
            className="input"
            placeholder="如 A-01"
            value={filters.pageNo}
            onChange={(e) => updateFilter('pageNo', e.target.value)}
          />
        </div>
      </div>
      
      <div className="mt-4 pt-4 border-t border-slate-200">
        <div className="flex items-center gap-4">
          <span className="text-sm text-slate-600">显示范围：</span>
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="radio"
              checked={filters.hasError === undefined}
              onChange={() => updateFilter('hasError', undefined)}
              className="text-primary-600"
            />
            <span className="text-sm">全部记录</span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="radio"
              checked={filters.hasError === false}
              onChange={() => updateFilter('hasError', false)}
              className="text-primary-600"
            />
            <span className="text-sm">正常记录</span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="radio"
              checked={filters.hasError === true}
              onChange={() => updateFilter('hasError', true)}
              className="text-primary-600"
            />
            <span className="text-sm">仅问题记录</span>
          </label>
        </div>
      </div>
    </div>
  );
}

// change-impact-dashboard/src/components/FilterPanel.vue
<template>
  <div class="bg-white rounded-xl shadow-sm border border-slate-200 p-4">
    <div class="flex items-center justify-between mb-4">
      <h3 class="text-sm font-semibold text-slate-700 flex items-center gap-2">
        <Filter class="w-4 h-4" />
        筛选条件
      </h3>
      <button 
        @click="store.change.resetFilters()"
        class="text-xs text-slate-500 hover:text-primary-600 transition-colors"
      >
        重置筛选
      </button>
    </div>
    
    <div class="space-y-3">
      <div>
        <label class="block text-xs text-slate-500 mb-1">关键词搜索</label>
        <input
          type="text"
          v-model="localFilters.keyword"
          @input="updateFilters()"
          class="input"
          placeholder="变更编号/标题/内容..."
        />
      </div>
      
      <div class="grid grid-cols-2 gap-2">
        <div>
          <label class="block text-xs text-slate-500 mb-1">责任专业</label>
          <select
            v-model="localFilters.major"
            @change="updateFilters()"
            class="select"
          >
            <option value="all">全部专业</option>
            <option v-for="m in MAJORS" :key="m.id" :value="m.id">{{ m.name }}</option>
          </select>
        </div>
        
        <div>
          <label class="block text-xs text-slate-500 mb-1">责任人</label>
          <select
            v-model="localFilters.responsiblePerson"
            @change="updateFilters()"
            class="select"
          >
            <option value="all">全部责任人</option>
            <option v-for="p in RESPONSIBLE_PERSONS" :key="p.id" :value="p.id">{{ p.name }}</option>
          </select>
        </div>
      </div>
      
      <div class="grid grid-cols-2 gap-2">
        <div>
          <label class="block text-xs text-slate-500 mb-1">影响等级</label>
          <select
            v-model="localFilters.impactLevel"
            @change="updateFilters()"
            class="select"
          >
            <option value="all">全部等级</option>
            <option v-for="i in IMPACT_LEVEL" :key="i.id" :value="i.id">{{ i.name }}</option>
          </select>
        </div>
        
        <div>
          <label class="block text-xs text-slate-500 mb-1">施工状态</label>
          <select
            v-model="localFilters.constructionStatus"
            @change="updateFilters()"
            class="select"
          >
            <option value="all">全部状态</option>
            <option v-for="s in CONSTRUCTION_STATUS" :key="s.id" :value="s.id">{{ s.name }}</option>
          </select>
        </div>
      </div>
      
      <div class="grid grid-cols-2 gap-2">
        <div>
          <label class="block text-xs text-slate-500 mb-1">处理状态</label>
          <select
            v-model="localFilters.status"
            @change="updateFilters()"
            class="select"
          >
            <option value="all">全部状态</option>
            <option v-for="s in CHANGE_STATUS" :key="s.id" :value="s.id">{{ s.name }}</option>
          </select>
        </div>
        
        <div>
          <label class="block text-xs text-slate-500 mb-1">来源类型</label>
          <select
            v-model="localFilters.sourceType"
            @change="updateFilters()"
            class="select"
          >
            <option value="all">全部来源</option>
            <option v-for="s in SOURCE_TYPES" :key="s.id" :value="s.id">{{ s.name }}</option>
          </select>
        </div>
      </div>
    </div>
    
    <div class="mt-4 pt-4 border-t border-slate-100">
      <div class="text-xs text-slate-500 flex items-center justify-between">
        <span>当前筛选结果</span>
        <span class="font-semibold text-slate-700">
          {{ store.change.filteredChanges.length }} 条
        </span>
      </div>
      <div class="text-xs text-slate-400 mt-1">
        待确认：{{ pendingCount }} 条
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed, watch } from 'vue';
import { Filter } from 'lucide-vue-next';
import { useChangeStore } from '../stores/changeStore';
import { 
  MAJORS, 
  RESPONSIBLE_PERSONS, 
  IMPACT_LEVEL, 
  CONSTRUCTION_STATUS, 
  CHANGE_STATUS, 
  SOURCE_TYPES 
} from '../data/constants';

const store = { change: useChangeStore() };

const localFilters = reactive({ ...store.change.filters });

const pendingCount = computed(() => 
  store.change.filteredChanges.filter(c => c.status === 'pending').length
);

const updateFilters = () => {
  store.change.setFilters({ ...localFilters });
};

watch(
  () => ({ ...store.change.filters }),
  (newFilters) => {
    Object.assign(localFilters, newFilters);
  },
  { deep: true }
);
</script>
